/* ----------------------------- WebGL render ----------------------------- */
const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'})||canvas.getContext('experimental-webgl');
if(!gl){alert('WebGL недоступен в этом браузере.');throw new Error('WebGL unavailable')}
const VS=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uMVP;uniform mat4 uModel;varying vec3 vN;varying vec3 vW;void main(){vec4 w=uModel*vec4(aPos,1.0);vW=w.xyz;vN=normalize(mat3(uModel)*aNormal);gl_Position=uMVP*vec4(aPos,1.0);}`;
const FS=`precision mediump float;varying vec3 vN;varying vec3 vW;uniform vec4 uColor;uniform vec3 uLight;uniform vec3 uEye;uniform float uRough;uniform float uMetal;uniform float uEmit;uniform vec3 uFog;void main(){vec3 N=normalize(vN),L=normalize(uLight),V=normalize(uEye-vW),H=normalize(L+V);float ndl=max(dot(N,L),0.0);float spec=pow(max(dot(N,H),0.0),mix(48.0,8.0,uRough))*mix(.18,.75,uMetal);float hemi=.56+.28*N.y;float rim=pow(1.0-max(dot(N,V),0.0),2.2)*.10;vec3 base=uColor.rgb*(hemi+.48*ndl)+spec+rim+uColor.rgb*uEmit;float fog=clamp((length(uEye-vW)-16.0)/35.0,0.0,1.0);gl_FragColor=vec4(mix(base,uFog,fog),uColor.a);}`;
function sh(type,src){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
const prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,VS));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,FS));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(prog));gl.useProgram(prog);
const L={pos:gl.getAttribLocation(prog,'aPos'),normal:gl.getAttribLocation(prog,'aNormal'),mvp:gl.getUniformLocation(prog,'uMVP'),model:gl.getUniformLocation(prog,'uModel'),color:gl.getUniformLocation(prog,'uColor'),light:gl.getUniformLocation(prog,'uLight'),eye:gl.getUniformLocation(prog,'uEye'),rough:gl.getUniformLocation(prog,'uRough'),metal:gl.getUniformLocation(prog,'uMetal'),emit:gl.getUniformLocation(prog,'uEmit'),fog:gl.getUniformLocation(prog,'uFog')};
gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.uniform3f(L.light,-.42,.88,.35);gl.uniform3f(L.fog,.58,.82,.94);
function mesh(data){let m={count:data.p.length/3};m.pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.p),gl.STATIC_DRAW);m.nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,m.nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.n),gl.STATIC_DRAW);return m}
function roundedBoxData(seg=3,rad=.12){let p=[],n=[];const faces=[{axis:0,sgn:1},{axis:0,sgn:-1},{axis:1,sgn:1},{axis:1,sgn:-1},{axis:2,sgn:1},{axis:2,sgn:-1}];let q=(f,u,v)=>{let a=[0,0,0],axes=[0,1,2].filter(x=>x!==f.axis);a[f.axis]=.5*f.sgn;a[axes[0]]=u-.5;a[axes[1]]=v-.5;let inn=a.map(x=>Math.max(-.5+rad,Math.min(.5-rad,x))),off=a.map((x,i)=>x-inn[i]),len=Math.hypot(...off);let nn=len>.0001?off.map(x=>x/len):[0,0,0];if(len<=.0001)nn[f.axis]=f.sgn;return{v:inn.map((x,i)=>x+nn[i]*rad),n:nn}};for(const f of faces){for(let iy=0;iy<seg;iy++)for(let ix=0;ix<seg;ix++){let u0=ix/seg,u1=(ix+1)/seg,v0=iy/seg,v1=(iy+1)/seg,A=q(f,u0,v0),B=q(f,u1,v0),C=q(f,u1,v1),D=q(f,u0,v1);let tri=f.sgn>0?[A,B,C,A,C,D]:[A,C,B,A,D,C];for(const t of tri){p.push(...t.v);n.push(...t.n)}}}return{p,n}}
function sphereData(seg=20,rings=14,noise=0){let p=[],n=[];const point=(ph,th)=>{let base={x:Math.sin(ph)*Math.cos(th),y:Math.cos(ph),z:Math.sin(ph)*Math.sin(th)};let k=1+noise*(.14*Math.sin(th*3.1+ph*4.7)+.08*Math.sin(th*6.2-ph*3.3));return{x:base.x*k,y:base.y*k,z:base.z*k,n:V.norm(base)}};for(let y=0;y<rings;y++){let ph0=y/rings*Math.PI,ph1=(y+1)/rings*Math.PI;for(let x=0;x<seg;x++){let th0=x/seg*Math.PI*2,th1=(x+1)/seg*Math.PI*2,A=point(ph0,th0),B=point(ph1,th0),C=point(ph1,th1),D=point(ph0,th1);for(const t of [A,B,C,A,C,D]){p.push(t.x,t.y,t.z);n.push(t.n.x,t.n.y,t.n.z)}}}return{p,n}}
function cylinderData(seg=24){let p=[],n=[];for(let i=0;i<seg;i++){let a=i/seg*Math.PI*2,b=(i+1)/seg*Math.PI*2,ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b);for(const t of [[ca,-.5,sa,ca,0,sa],[ca,.5,sa,ca,0,sa],[cb,.5,sb,cb,0,sb],[ca,-.5,sa,ca,0,sa],[cb,.5,sb,cb,0,sb],[cb,-.5,sb,cb,0,sb]]){p.push(t[0],t[1],t[2]);n.push(t[3],t[4],t[5])}for(const yy of [-.5,.5]){let s=yy>0?1:-1,tri=s>0?[[0,yy,0],[cb,yy,sb],[ca,yy,sa]]:[[0,yy,0],[ca,yy,sa],[cb,yy,sb]];for(const t of tri){p.push(...t);n.push(0,s,0)}}}return{p,n}}
const meshes={box:mesh(roundedBoxData(4,.13)),boxSoft:mesh(roundedBoxData(5,.2)),sphere:mesh(sphereData()),boulder:mesh(sphereData(18,12,.55)),cyl:mesh(cylinderData())};
let VP=M4.I(),camera={eye:V.v(8,6.6,11.5),target:V.v(8,1,0),right:V.v(1,0,0),up:V.v(0,1,0),forward:V.v(1,0,0),fov:48*Math.PI/180};
function drawMat(meshObj,p,s,r,color,rough=.7,metal=.05,emit=0,alpha=1,modelOverride=null){let model=modelOverride||M4.TRS(p,r,s),mvp=M4.mul(VP,model);gl.uniformMatrix4fv(L.model,false,model);gl.uniformMatrix4fv(L.mvp,false,mvp);gl.uniform4fv(L.color,hex(color,alpha));gl.uniform1f(L.rough,rough);gl.uniform1f(L.metal,metal);gl.uniform1f(L.emit,emit);gl.bindBuffer(gl.ARRAY_BUFFER,meshObj.pb);gl.enableVertexAttribArray(L.pos);gl.vertexAttribPointer(L.pos,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,meshObj.nb);gl.enableVertexAttribArray(L.normal);gl.vertexAttribPointer(L.normal,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.TRIANGLES,0,meshObj.count)}
function drawBetween(a,b,width,color,rough=.7,metal=.05){let d=V.sub(b,a),len=V.len(d);if(len<.001)return;let y=V.norm(d),seed=Math.abs(y.z)<.9?V.v(0,0,1):V.v(1,0,0),x=V.norm(V.cross(seed,y)),z=V.cross(x,y),m=M4.basis(V.mul(V.add(a,b),.5),x,y,z,V.v(width,len,width));drawMat(meshes.cyl,V.v(),V.v(1,1,1),V.v(),color,rough,metal,0,1,m)}

