/* ------------------------------ physics core ------------------------------ */
const MAT={wood:{fric:5.2,rest:.12},metal:{fric:3.1,rest:.08},plastic:{fric:4.2,rest:.18},rubber:{fric:7.5,rest:.56},stone:{fric:6.2,rest:.05},fabric:{fric:6.4,rest:.06}};
let bodies=[],statics=[],particles=[];
let bodyId=1;
function body(def){let b={id:bodyId++,name:def.name,mass:def.mass,inv:def.mass?1/def.mass:0,pos:V.v(def.x,def.y,def.z),prev:V.v(def.x,def.y,def.z),vel:V.v(),rot:V.v(def.rx||0,def.ry||0,def.rz||0),ang:V.v(),colliders:def.colliders||[{c:V.v(),h:V.v(.5,.5,.5)}],sphere:def.sphere||0,material:def.material||'wood',color:def.color||'#ddd',model:def.model,gripForce:def.gripForce||Math.max(110,420-def.mass*2.2),lift:!!def.lift,throwable:def.throwable!==false,grounded:false,lastImpact:0,hover:false,selected:false,tag:def.tag||'',sleep:0};b.inertia=Math.max(.4,def.mass*(def.inertia||.35));b.invInertia=1/b.inertia;bodies.push(b);return b}
function staticBox(x,y,z,sx,sy,sz,opt={}){let s={x,y,z,sx,sy,sz,color:opt.color||'#dbe3ef',material:opt.material||'stone',kind:opt.kind||'wall',metal:opt.metal||0,rough:opt.rough??.72,emit:opt.emit||0,visible:opt.visible!==false};statics.push(s);return s}
function colliderAABB(b,c){let center=V.add(b.pos,rotate(c.c,b.rot)),hx=c.h.x,hy=c.h.y,hz=c.h.z;let cx=Math.cos(b.rot.x),sx=Math.sin(b.rot.x),cy=Math.cos(b.rot.y),sy=Math.sin(b.rot.y),cz=Math.cos(b.rot.z),sz=Math.sin(b.rot.z);
  let m00=cy*cz+sy*sx*sz,m01=-cy*sz+sy*sx*cz,m02=sy*cx,m10=cx*sz,m11=cx*cz,m12=-sx,m20=-sy*cz+cy*sx*sz,m21=sy*sz+cy*sx*cz,m22=cy*cx;
  return{c:center,h:V.v(Math.abs(m00)*hx+Math.abs(m01)*hy+Math.abs(m02)*hz,Math.abs(m10)*hx+Math.abs(m11)*hy+Math.abs(m12)*hz,Math.abs(m20)*hx+Math.abs(m21)*hy+Math.abs(m22)*hz)} }
function combinedAABB(b){if(b.sphere)return{c:b.pos,h:V.v(b.sphere,b.sphere,b.sphere)};let min=V.v(1e9,1e9,1e9),max=V.v(-1e9,-1e9,-1e9);for(const c of b.colliders){let a=colliderAABB(b,c);min.x=Math.min(min.x,a.c.x-a.h.x);min.y=Math.min(min.y,a.c.y-a.h.y);min.z=Math.min(min.z,a.c.z-a.h.z);max.x=Math.max(max.x,a.c.x+a.h.x);max.y=Math.max(max.y,a.c.y+a.h.y);max.z=Math.max(max.z,a.c.z+a.h.z)}return{c:V.mul(V.add(min,max),.5),h:V.mul(V.sub(max,min),.5)}}
function aabbOverlap(a,b){let dx=a.h.x+b.h.x-Math.abs(a.c.x-b.c.x),dy=a.h.y+b.h.y-Math.abs(a.c.y-b.c.y),dz=a.h.z+b.h.z-Math.abs(a.c.z-b.c.z);return dx>0&&dy>0&&dz>0?{dx,dy,dz}:null}
function applyImpulse(b,imp,point=b.pos){if(!b.inv)return;b.vel.x+=imp.x*b.inv;b.vel.y+=imp.y*b.inv;b.vel.z+=imp.z*b.inv;let r=V.sub(point,b.pos),t=V.cross(r,imp);b.ang.x+=t.x*b.invInertia;b.ang.y+=t.y*b.invInertia;b.ang.z+=t.z*b.invInertia;b.sleep=0}
function applyForce(b,f,point,dt){applyImpulse(b,V.mul(f,dt),point)}
function resolveStatic(b,s){let impact=0,normal=null,pen=0;const sa={c:V.v(s.x,s.y,s.z),h:V.v(s.sx/2,s.sy/2,s.sz/2)};let cols=b.sphere?[{c:V.v(),h:V.v(b.sphere,b.sphere,b.sphere)}]:b.colliders;for(const c of cols){let a=b.sphere?{c:b.pos,h:V.v(b.sphere,b.sphere,b.sphere)}:colliderAABB(b,c),o=aabbOverlap(a,sa);if(!o)continue;let axis='x',m=o.dx;if(o.dy<m){m=o.dy;axis='y'}if(o.dz<m){m=o.dz;axis='z'}let sign=Math.sign(a.c[axis]-sa.c[axis])||1,n=V.v();n[axis]=sign;b.pos[axis]+=sign*m+.0005;let vn=V.dot(b.vel,n);impact=Math.max(impact,Math.abs(vn));if(vn<0){let rest=MAT[b.material]?.rest??.1;b.vel=V.sub(b.vel,V.mul(n,(1+rest)*vn));b.vel.x*=axis==='y'?.94:.82;b.vel.z*=axis==='y'?.94:.82;if(axis==='y'&&sign>0)b.grounded=true}normal=n;pen=m}
  if(impact>2.1)registerImpact(b,impact,s.material||'stone');return{impact,normal,pen}}
function resolveBodyPair(a,b){if(a===b)return;let A=combinedAABB(a),B=combinedAABB(b),o=aabbOverlap(A,B);if(!o)return;let axis='x',m=o.dx;if(o.dy<m){m=o.dy;axis='y'}if(o.dz<m){m=o.dz;axis='z'}let sign=Math.sign(A.c[axis]-B.c[axis])||1,n=V.v();n[axis]=sign,inv=a.inv+b.inv;if(!inv)return;a.pos[axis]+=sign*m*(a.inv/inv);b.pos[axis]-=sign*m*(b.inv/inv);let rel=V.sub(a.vel,b.vel),vn=V.dot(rel,n);if(vn<0){let e=Math.min(MAT[a.material]?.rest??.1,MAT[b.material]?.rest??.1),j=-(1+e)*vn/inv,imp=V.mul(n,j);applyImpulse(a,imp);applyImpulse(b,V.mul(imp,-1));let tang=V.sub(rel,V.mul(n,vn)),tl=V.len(tang);if(tl>.01){let t=V.mul(tang,1/tl),jf=Math.min(j*.28,tl/inv),f=V.mul(t,-jf);applyImpulse(a,f);applyImpulse(b,V.mul(f,-1))}if(Math.abs(vn)>2.4){registerImpact(a,Math.abs(vn),b.material);registerImpact(b,Math.abs(vn),a.material)}}
}
function registerImpact(b,force,otherMat){let now=performance.now();if(now-b.lastImpact<110)return;b.lastImpact=now;impactSound(otherMat||b.material,force);let words=force>8?['БДЫЩ!','БАМ!','БУМ!']:['ТУК','БОНК','КЛАЦ'];boom(words[(Math.random()*words.length)|0],force);spawnDust(b.pos,force,b.material);if(b.tag==='boxA'||b.tag==='boxB')checks.boxes=true;if(force>3.2)checks.throw=true}
function spawnDust(p,force,mat){let c=mat==='metal'?'#d9efff':mat==='wood'?'#e8bd7c':'#d9e0ea';for(let i=0;i<Math.min(8,2+(force|0));i++)particles.push({p:V.add(p,V.v((Math.random()-.5)*.6,.15,(Math.random()-.5)*.6)),v:V.v((Math.random()-.5)*1.8,Math.random()*1.4,(Math.random()-.5)*1.8),life:.35+Math.random()*.25,c})}
function physicsStep(dt){for(const b of bodies){b.prev={...b.pos};b.grounded=false;if(!b.inv)continue;b.vel.y-=9.81*dt;b.pos.x+=b.vel.x*dt;b.pos.y+=b.vel.y*dt;b.pos.z+=b.vel.z*dt;b.rot.x+=b.ang.x*dt;b.rot.y+=b.ang.y*dt;b.rot.z+=b.ang.z*dt;for(const s of statics)resolveStatic(b,s);let fr=MAT[b.material]?.fric??4;if(b.grounded){let k=Math.exp(-fr*dt);b.vel.x*=k;b.vel.z*=k;b.ang.x*=Math.exp(-2.2*dt);b.ang.z*=Math.exp(-2.2*dt)}b.ang.y*=Math.exp(-.8*dt);b.ang.x*=Math.exp(-.65*dt);b.ang.z*=Math.exp(-.65*dt);if(b.sphere&&b.grounded){b.ang.z=-b.vel.x/Math.max(.1,b.sphere);b.ang.x=b.vel.z/Math.max(.1,b.sphere)}if(b.pos.y<-5){resetBody(b)}}for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++)resolveBodyPair(bodies[i],bodies[j]);}

