'use strict';
(()=>{const G=window.GAME;
const V={v:(x=0,y=0,z=0)=>({x,y,z}),add:(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}),sub:(a,b)=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}),mul:(a,s)=>({x:a.x*s,y:a.y*s,z:a.z*s}),dot:(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,cross:(a,b)=>({x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x}),len:a=>Math.hypot(a.x,a.y,a.z),norm:a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return{x:a.x/l,y:a.y/l,z:a.z/l}},lerp:(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t}),clampLen:(a,m)=>{const l=Math.hypot(a.x,a.y,a.z);return l>m&&l?{x:a.x*m/l,y:a.y*m/l,z:a.z*m/l}:{...a}}};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),lerp=(a,b,t)=>a+(b-a)*t,wrap=a=>{while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a};
const rot2=(x,z,a)=>({x:x*Math.cos(a)-z*Math.sin(a),z:x*Math.sin(a)+z*Math.cos(a)});
const invRot2=(x,z,a)=>rot2(x,z,-a);
function axes2(o){const c=Math.cos(o.yaw||0),s=Math.sin(o.yaw||0);return[{x:c,z:s},{x:-s,z:c}]}
function projRadius(o,n){const a=axes2(o);return Math.abs(a[0].x*n.x+a[0].z*n.z)*(o.w/2)+Math.abs(a[1].x*n.x+a[1].z*n.z)*(o.d/2)}
function support2(o,n){const a=axes2(o),sx=(a[0].x*n.x+a[0].z*n.z)>=0?o.w/2:-o.w/2,sz=(a[1].x*n.x+a[1].z*n.z)>=0?o.d/2:-o.d/2;return{x:o.pos.x+a[0].x*sx+a[1].x*sz,z:o.pos.z+a[0].z*sx+a[1].z*sz}}
function sat2(A,B){const tests=[...axes2(A),...axes2(B)],dx=A.pos.x-B.pos.x,dz=A.pos.z-B.pos.z;let depth=1e9,n=null;for(const t0 of tests){const l=Math.hypot(t0.x,t0.z)||1,t={x:t0.x/l,z:t0.z/l},ov=projRadius(A,t)+projRadius(B,t)-Math.abs(dx*t.x+dz*t.z);if(ov<=0)return null;if(ov<depth){depth=ov;const sign=(dx*t.x+dz*t.z)>=0?1:-1;n={x:t.x*sign,z:t.z*sign}}}const pa=support2(A,{x:-n.x,z:-n.z}),pb=support2(B,n);return{depth,n,p:{x:(pa.x+pb.x)/2,z:(pa.z+pb.z)/2}}}
function segmentAABB(a,b,s){let t0=0,t1=1;const d={x:b.x-a.x,y:b.y-a.y,z:b.z-a.z};for(const k of ['x','y','z']){const min=s[k]-s['s'+k]/2,max=s[k]+s['s'+k]/2;if(Math.abs(d[k])<1e-8){if(a[k]<min||a[k]>max)return null;continue}let u0=(min-a[k])/d[k],u1=(max-a[k])/d[k];if(u0>u1)[u0,u1]=[u1,u0];t0=Math.max(t0,u0);t1=Math.min(t1,u1);if(t0>t1)return null}return t0}
const M4={I(){const o=new Float32Array(16);o[0]=o[5]=o[10]=o[15]=1;return o},mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o},perspective(fovy,asp,n,f){const q=1/Math.tan(fovy/2),nf=1/(n-f),o=new Float32Array(16);o[0]=q/asp;o[5]=q;o[10]=(f+n)*nf;o[11]=-1;o[14]=2*f*n*nf;return o},lookAt(e,t,u){const z=V.norm(V.sub(e,t)),x=V.norm(V.cross(u,z)),y=V.cross(z,x),o=this.I();o[0]=x.x;o[1]=y.x;o[2]=z.x;o[4]=x.y;o[5]=y.y;o[6]=z.y;o[8]=x.z;o[9]=y.z;o[10]=z.z;o[12]=-V.dot(x,e);o[13]=-V.dot(y,e);o[14]=-V.dot(z,e);return o},TRS(p,r,s){const cx=Math.cos(r.x),sx=Math.sin(r.x),cy=Math.cos(r.y),sy=Math.sin(r.y),cz=Math.cos(r.z),sz=Math.sin(r.z),o=this.I();o[0]=(cy*cz+sy*sx*sz)*s.x;o[1]=cx*sz*s.x;o[2]=(-sy*cz+cy*sx*sz)*s.x;o[4]=(-cy*sz+sy*sx*cz)*s.y;o[5]=cx*cz*s.y;o[6]=(sy*sz+cy*sx*cz)*s.y;o[8]=sy*cx*s.z;o[9]=-sx*s.z;o[10]=cy*cx*s.z;o[12]=p.x;o[13]=p.y;o[14]=p.z;return o},basis(p,x,y,z,s){const o=this.I();o[0]=x.x*s.x;o[1]=x.y*s.x;o[2]=x.z*s.x;o[4]=y.x*s.y;o[5]=y.y*s.y;o[6]=y.z*s.y;o[8]=z.x*s.z;o[9]=z.y*s.z;o[10]=z.z*s.z;o[12]=p.x;o[13]=p.y;o[14]=p.z;return o}};
const hex=(h,a=1)=>{h=h.replace('#','');return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255,a]};
Object.assign(G,{V,clamp,lerp,wrap,rot2,invRot2,axes2,projRadius,support2,sat2,segmentAABB,M4,hex});})();
