'use strict';
(()=>{const G=window.GAME,S=G.state,{V,clamp,lerp,wrap,sat2,projRadius}=G;
const MATERIALS={wood:{friction:.54,restitution:.10},metal:{friction:.36,restitution:.05},fabric:{friction:.72,restitution:.03},rubber:{friction:.88,restitution:.42},stone:{friction:.62,restitution:.02},plastic:{friction:.45,restitution:.12}};G.MATERIALS=MATERIALS;
let nextId=1;
G.makeBody=d=>{const m=d.mass||1,w=d.w||1,dep=d.d||1,h=d.h||1,I=m*(w*w+dep*dep)/12*(d.inertiaScale||1);return{id:nextId++,name:d.name||'ГРУЗ',tag:d.tag||'',model:d.model||'box',pos:V.v(d.x||0,d.y??h/2,d.z||0),spawn:V.v(d.x||0,d.y??h/2,d.z||0),vel:V.v(),yaw:d.yaw||0,spawnYaw:d.yaw||0,ang:0,w,d:dep,h,mass:m,inv:1/m,I,invI:1/I,material:d.material||'wood',color:d.color||'#ccc',accent:d.accent||'#777',profile:d.profile||{},grounded:false,sleepTime:0,sleeping:false,selected:false,hover:false,roll:0,tilt:0,tiltVel:0,objective:!!d.objective};};
G.makeStatic=(x,y,z,sx,sy,sz,opt={})=>({pos:V.v(x,y,z),x,y,z,sx,sy,sz,w:sx,d:sz,h:sy,yaw:opt.yaw||0,material:opt.material||'stone',color:opt.color||'#dbe4ea',kind:opt.kind||'wall',visible:opt.visible!==false,rough:opt.rough??.75,metal:opt.metal??0,emit:opt.emit??0,fade:1});
G.addImpulse=(b,j,p={x:b.pos.x,z:b.pos.z})=>{if(!b||!b.inv)return;b.vel.x+=j.x*b.inv;b.vel.z+=j.z*b.inv;const rx=p.x-b.pos.x,rz=p.z-b.pos.z;b.ang+=(rx*j.z-rz*j.x)*b.invI;b.sleeping=false;b.sleepTime=0};
G.addForce=(b,f,p,dt)=>G.addImpulse(b,{x:f.x*dt,z:f.z*dt},p);
function verticalOverlapBodyStatic(b,s){const b0=b.pos.y-b.h/2,b1=b.pos.y+b.h/2,s0=s.y-s.sy/2,s1=s.y+s.sy/2;return Math.min(b1,s1)-Math.max(b0,s0)}
function staticAsOBB(s){return{pos:{x:s.x,z:s.z},w:s.sx,d:s.sz,yaw:s.yaw||0}}
function contactVel(b,p){const rx=p.x-b.pos.x,rz=p.z-b.pos.z;return{x:b.vel.x-b.ang*rz,z:b.vel.z+b.ang*rx}}
function applyContactImpulse(A,B,c,materialB){const n=c.n,p=c.p,va=contactVel(A,p),vb=B?contactVel(B,p):{x:0,z:0},rv={x:va.x-vb.x,z:va.z-vb.z},vn=rv.x*n.x+rv.z*n.z;if(vn>=0)return;const ra={x:p.x-A.pos.x,z:p.z-A.pos.z},rb=B?{x:p.x-B.pos.x,z:p.z-B.pos.z}:{x:0,z:0},raN=ra.x*n.z-ra.z*n.x,rbN=rb.x*n.z-rb.z*n.x,inv=(A.inv||0)+(B?.inv||0)+raN*raN*(A.invI||0)+rbN*rbN*(B?.invI||0),e=Math.min(MATERIALS[A.material]?.restitution??.05,MATERIALS[materialB||B?.material]?.restitution??.05),jn=-(1+e)*vn/Math.max(inv,1e-6),j={x:n.x*jn,z:n.z*jn};G.addImpulse(A,j,p);if(B)G.addImpulse(B,{x:-j.x,z:-j.z},p);
 const rv2={x:contactVel(A,p).x-(B?contactVel(B,p).x:0),z:contactVel(A,p).z-(B?contactVel(B,p).z:0)},t0={x:rv2.x-n.x*(rv2.x*n.x+rv2.z*n.z),z:rv2.z-n.z*(rv2.x*n.x+rv2.z*n.z)},tl=Math.hypot(t0.x,t0.z);if(tl>.0005){const t={x:t0.x/tl,z:t0.z/tl},raT=ra.x*t.z-ra.z*t.x,rbT=rb.x*t.z-rb.z*t.x,den=(A.inv||0)+(B?.inv||0)+raT*raT*(A.invI||0)+rbT*rbT*(B?.invI||0),mu=Math.sqrt((MATERIALS[A.material]?.friction??.5)*(MATERIALS[materialB||B?.material]?.friction??.5)),jt=clamp(-(rv2.x*t.x+rv2.z*t.z)/Math.max(den,1e-6),-jn*mu,jn*mu),fj={x:t.x*jt,z:t.z*jt};G.addImpulse(A,fj,p);if(B)G.addImpulse(B,{x:-fj.x,z:-fj.z},p)}
 if(Math.abs(vn)>2.2&&S.impactCooldown<=0){S.impactCooldown=.08;G.toast(Math.abs(vn)>7?'БДЫЩ!':Math.abs(vn)>4?'БОНК!':'ТУК',Math.abs(vn));G.impactSound?.(A.material,Math.abs(vn))}}
G.resolveBodyStatic=(b,s)=>{const stepTop=s.y+s.sy/2;if(s.kind==='step'&&stepTop<=b.pos.y-b.h/2+.38)return false;if(verticalOverlapBodyStatic(b,s)<=.02)return false;const c=sat2(b,staticAsOBB(s));if(!c)return false;const correction=Math.max(0,c.depth-.002)*.88;b.pos.x+=c.n.x*correction;b.pos.z+=c.n.z*correction;applyContactImpulse(b,null,c,s.material);return true};
G.resolveBodyPair=(a,b)=>{const yov=Math.min(a.pos.y+a.h/2,b.pos.y+b.h/2)-Math.max(a.pos.y-a.h/2,b.pos.y-b.h/2);if(yov<=.02)return false;const c=sat2(a,b);if(!c)return false;const inv=a.inv+b.inv,corr=Math.max(0,c.depth-.002)*.82/Math.max(inv,1e-6);a.pos.x+=c.n.x*corr*a.inv;a.pos.z+=c.n.z*corr*a.inv;b.pos.x-=c.n.x*corr*b.inv;b.pos.z-=c.n.z*corr*b.inv;applyContactImpulse(a,b,c,b.material);return true};
G.floorHeight=(x,z)=>{let top=0;for(const s of S.statics){if(s.kind==='ceiling')continue;if(x<s.x-s.sx/2||x>s.x+s.sx/2||z<s.z-s.sz/2||z>s.z+s.sz/2)continue;const t=s.y+s.sy/2;if(t<=2.4)top=Math.max(top,t)}return top};
function integrateVertical(b,dt){if(b.sleeping)return;const g=b.profile.gravityScale??1;b.vel.y-=9.81*g*dt;b.pos.y+=b.vel.y*dt;const floor=G.floorHeight(b.pos.x,b.pos.z),bottom=b.pos.y-b.h/2;if(bottom<floor){const impact=-b.vel.y;b.pos.y= floor+b.h/2;if(b.vel.y<0)b.vel.y=impact>1.2?impact*(MATERIALS[b.material]?.restitution??.05):0;b.grounded=true;if(impact>3.2&&S.impactCooldown<=0){S.impactCooldown=.08;G.toast(impact>6?'БУМ!':'ТУК',impact);G.impactSound?.(b.material,impact)}}else b.grounded=false}
function integratePlanar(b,dt){if(b.sleeping)return;const ld=b.profile.linearDamping??.75,ad=b.profile.angularDamping??1.15;b.vel.x*=Math.exp(-ld*dt);b.vel.z*=Math.exp(-ld*dt);b.ang*=Math.exp(-ad*dt);b.pos.x+=b.vel.x*dt;b.pos.z+=b.vel.z*dt;b.yaw=wrap(b.yaw+b.ang*dt);if(b.profile.rollable&&b.grounded){const speed=Math.hypot(b.vel.x,b.vel.z);b.roll+=speed*dt/Math.max(.35,b.profile.rollRadius||.65)}b.tiltVel*=Math.exp(-3.2*dt);b.tilt+=b.tiltVel*dt;b.tilt*=Math.exp(-2.5*dt)}
function applyGroundFriction(b,dt){if(!b.grounded||b.sleeping)return;const mu=MATERIALS[b.material]?.friction??.5,roll=b.profile.rollable?(b.profile.rollingResistance??.18):1,k=Math.exp(-mu*4.0*roll*dt);b.vel.x*=k;b.vel.z*=k;b.ang*=Math.exp(-(b.profile.rollable?.45:2.2)*dt)}
function updateSleep(b,dt){if(!b.grounded){b.sleepTime=0;b.sleeping=false;return}const slow=Math.hypot(b.vel.x,b.vel.z)<.025&&Math.abs(b.vel.y)<.03&&Math.abs(b.ang)<.018;if(slow)b.sleepTime+=dt;else b.sleepTime=0;if(b.sleepTime>.72){b.sleeping=true;b.vel.x=b.vel.y=b.vel.z=0;b.ang=0;b.tiltVel=0}}
G.physicsSubsteps=dt=>{let worst=1;for(const b of S.bodies){const r=Math.max(.2,Math.min(b.w,b.d)*.5),travel=Math.hypot(b.vel.x,b.vel.z)*dt/r,turn=Math.abs(b.ang)*dt*Math.max(b.w,b.d)/r;worst=Math.max(worst,travel*2.2,turn*1.4)}return clamp(Math.ceil(worst),1,12)};
G.physicsStep=dt=>{S.impactCooldown-=dt;for(const b of S.bodies){integrateVertical(b,dt);integratePlanar(b,dt);for(let p=0;p<3;p++)for(const s of S.statics)G.resolveBodyStatic(b,s);applyGroundFriction(b,dt)}for(let p=0;p<3;p++)for(let i=0;i<S.bodies.length;i++)for(let j=i+1;j<S.bodies.length;j++)G.resolveBodyPair(S.bodies[i],S.bodies[j]);for(const b of S.bodies){updateSleep(b,dt);if(!Number.isFinite(b.pos.x+b.pos.y+b.pos.z+b.yaw+b.ang)||Math.abs(b.pos.x)>80||Math.abs(b.pos.z)>40||b.pos.y<-8)G.resetBody(b)}};
G.stepPhysics=dt=>{const n=G.physicsSubsteps(dt),sd=dt/n;for(let i=0;i<n;i++){G.updateGrip?.(sd);G.physicsStep(sd)}};
G.resetBody=b=>{b.pos={...b.spawn};b.vel=V.v();b.yaw=b.spawnYaw;b.ang=0;b.sleeping=false;b.sleepTime=0;b.tilt=0;b.tiltVel=0;if(S.grip?.body===b)G.releaseGrip?.(false)};
G.bodyInsideGoal=b=>{if(!S.goal)return false;const gx=S.goal.x,gz=S.goal.z,rx=projRadius(b,{x:1,z:0}),rz=projRadius(b,{x:0,z:1});return Math.abs(b.pos.x-gx)+rx<S.goal.w/2+.22&&Math.abs(b.pos.z-gz)+rz<S.goal.d/2+.22&&Math.hypot(b.vel.x,b.vel.z)<1.1};
})();
