'use strict';
(()=>{const G=window.GAME,S=G.state,canvas=G.canvas;const GAME_KEYS=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyQ','KeyE','KeyR','Escape']);
S.pointer={down:false,id:null,x:0,y:0,startX:0,startY:0,lastX:0,lastY:0,startT:0,lastT:0,moved:0,target:null,held:false,holdTimer:0,dragX:0,dragY:0,releaseSpeed:0,releaseDir:null,hist:[],camera:false};const P=S.pointer;
function cancelHold(){if(P.holdTimer){clearTimeout(P.holdTimer);P.holdTimer=0}}
addEventListener('keydown',e=>{S.keys[e.code]=true;if(GAME_KEYS.has(e.code))e.preventDefault();if(e.code==='Space')G.jump();if(e.code==='KeyQ')S.rotateInput=-1;if(e.code==='KeyE')S.rotateInput=1;if(e.code==='KeyR'&&S.mode==='playing')G.loadLevel(S.levelIndex,{lab:S.levelIsLab});if(e.code==='Escape')G.togglePause?.()});
addEventListener('keyup',e=>{S.keys[e.code]=false;if(e.code==='KeyQ'&&S.rotateInput<0)S.rotateInput=0;if(e.code==='KeyE'&&S.rotateInput>0)S.rotateInput=0});
function startPointer(e){if(S.mode!=='playing'||S.paused||P.down)return;e.preventDefault();G.ensureAudio?.();P.down=true;P.id=e.pointerId;P.x=P.lastX=P.startX=e.clientX;P.y=P.lastY=P.startY=e.clientY;P.startT=P.lastT=performance.now();P.moved=0;P.held=false;P.dragX=P.dragY=0;P.releaseSpeed=0;P.releaseDir=null;P.hist=[];const g=G.screenGround(e.clientX,e.clientY);P.hist.push({x:g.x,z:g.z,t:P.startT});P.target=G.pickBody(e.clientX,e.clientY);P.camera=e.button===2||!P.target;try{canvas.setPointerCapture(e.pointerId)}catch{};for(const b of S.bodies)b.hover=false;if(P.target){P.target.body.hover=true;G.UI.interaction.classList.remove('hidden');G.UI.interactionTitle.textContent=`${P.target.body.name} · ${P.target.body.mass} КГ`;G.UI.interactionText.textContent='Клик — толкнуть · удержать — схватить';if(G.canReach(P.target.body)){P.holdTimer=setTimeout(()=>{P.holdTimer=0;if(P.down&&P.id===e.pointerId&&P.moved<20&&G.startGrip(P.target)){P.held=true}},190)}}}
function movePointer(e){if(!P.down||e.pointerId!==P.id)return;e.preventDefault();const now=performance.now(),dx=e.clientX-P.lastX,dy=e.clientY-P.lastY;P.x=e.clientX;P.y=e.clientY;P.moved=Math.max(P.moved,Math.hypot(P.x-P.startX,P.y-P.startY));P.dragX=clamp((P.x-P.startX)/Math.max(160,innerWidth*.25),-1,1);P.dragY=clamp((P.y-P.startY)/Math.max(140,innerHeight*.25),-1,1);const g=G.screenGround(e.clientX,e.clientY),last=P.hist[P.hist.length-1];if(!last||now-last.t>12){P.hist.push({x:g.x,z:g.z,t:now});if(P.hist.length>8)P.hist.shift()}if(P.camera&&P.moved>10)G.camera.orbit+=dx*.0065;else if(!P.held&&P.moved>22){cancelHold();P.camera=true;G.camera.orbit+=dx*.0065}P.lastX=P.x;P.lastY=P.y;P.lastT=now}
function finishPointer(e,cancelled=false){if(!P.down||e.pointerId!==P.id)return;e.preventDefault();cancelHold();const wasHeld=P.held,target=P.target,moved=P.moved;try{canvas.releasePointerCapture(e.pointerId)}catch{};if(P.hist.length>=2){const a=P.hist[Math.max(0,P.hist.length-4)],b=P.hist[P.hist.length-1],dt=Math.max(.016,(b.t-a.t)/1000),vx=(b.x-a.x)/dt,vz=(b.z-a.z)/dt,sp=Math.hypot(vx,vz);P.releaseSpeed=sp;P.releaseDir=sp>.001?{x:vx/sp,z:vz/sp}:null}else{P.releaseSpeed=0;P.releaseDir=null}if(cancelled){if(S.grip)G.releaseGrip(false)}else if(wasHeld&&S.grip)G.releaseGrip(true);else if(target&&!P.camera&&moved<14)G.tapPush(target);P.down=false;P.id=null;P.target=null;P.held=false;P.camera=false;P.hist=[];P.dragX=P.dragY=0;for(const b of S.bodies)b.hover=false;G.UI.interaction.classList.add('hidden')}
canvas.addEventListener('pointerdown',startPointer);canvas.addEventListener('pointermove',movePointer);canvas.addEventListener('pointerup',e=>finishPointer(e,false));canvas.addEventListener('pointercancel',e=>finishPointer(e,true));canvas.addEventListener('contextmenu',e=>e.preventDefault());
const joy=G.UI.joy,stick=G.UI.stick;let joyId=null;function joyMove(e){const r=joy.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=Math.hypot(x,y),mx=40,k=m>mx?mx/Math.max(m,1):1,xx=x*k,yy=y*k;S.joy.x=xx/mx;S.joy.z=yy/mx;stick.style.transform=`translate(${xx}px,${yy}px)`}joy.addEventListener('pointerdown',e=>{if(S.mode!=='playing'||S.paused||joyId!==null)return;e.preventDefault();e.stopPropagation();joyId=e.pointerId;try{joy.setPointerCapture(e.pointerId)}catch{};joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId){e.preventDefault();joyMove(e)}});const joyEnd=e=>{if(e.pointerId!==joyId)return;joyId=null;S.joy={x:0,z:0};stick.style.transform=''};joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);
G.UI.jump.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();G.jump()});for(const [el,val] of [[G.UI.rotL,-1],[G.UI.rotR,1]]){el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();S.rotateInput=val});el.addEventListener('pointerup',()=>S.rotateInput=0);el.addEventListener('pointercancel',()=>S.rotateInput=0)}
const oldReset=G.resetInput;G.resetInput=()=>{cancelHold();joyId=null;P.down=false;P.id=null;P.target=null;P.held=false;P.camera=false;P.dragX=P.dragY=0;oldReset?.()};addEventListener('blur',G.resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden)G.resetInput()});
})();
