import fs from 'node:fs';import vm from 'node:vm';
const ctx={console,window:{GAME:{state:{bodies:[],statics:[],impactCooldown:0,effects:[]},toast(){},impactSound(){}}}};vm.createContext(ctx);for(const f of ['src/overhaul/01-math.js','src/overhaul/02-physics.js','src/overhaul/02-physics-v2.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});const G=ctx.window.GAME,S=G.state;
let failures=[];const finite=b=>Number.isFinite(b.pos.x+b.pos.y+b.pos.z+b.yaw+b.ang+b.vel.x+b.vel.y+b.vel.z);function reset(){S.bodies=[];S.statics=[];S.impactCooldown=0;S.effects=[]}
reset();let b=G.makeBody({name:'rest',w:1.2,d:1.0,h:1.0,mass:20,x:0,y:.5,z:0,material:'wood'});S.bodies=[b];for(let i=0;i<1200;i++)G.stepPhysics(1/120);if(!finite(b)||Math.abs(b.ang)>.002||Math.hypot(b.vel.x,b.vel.z)>.003||!b.sleeping)failures.push('resting body did not settle/sleep');
reset();b=G.makeBody({name:'fast',w:1,d:1,h:1,mass:10,x:-3,y:.5,z:0,material:'wood'});b.vel.x=45;S.bodies=[b];S.statics=[G.makeStatic(0,1.3,0,.4,2.6,5,{material:'stone'})];for(let i=0;i<12;i++)G.stepPhysics(1/30);if(!finite(b)||b.pos.x>.8)failures.push(`tunneling through wall x=${b.pos.x}`);
reset();b=G.makeBody({name:'extreme',w:.72,d:2.6,h:1,mass:18,x:-6,y:.5,z:-.2,yaw:.55,material:'wood',profile:{angularDamping:.6}});b.vel.x=180;b.vel.z=8;b.ang=14;S.bodies=[b];S.statics=[G.makeStatic(0,1.2,0,.18,2.4,7,{material:'stone',yaw:.34})];for(let i=0;i<5;i++)G.stepPhysics(1/20);if(!finite(b)||b.pos.x>2.0)failures.push(`extreme swept CCD failed x=${b.pos.x}`);
reset();b=G.makeBody({name:'ceiling',w:1,d:1,h:1,mass:8,x:0,y:.5,z:0,material:'wood'});b.vel.y=20;S.bodies=[b];S.statics=[G.makeStatic(0,2.5,0,5,.4,5,{kind:'ceiling',material:'stone'})];for(let i=0;i<30;i++)G.stepPhysics(1/120);if(!finite(b)||b.pos.y+b.h/2>2.31)failures.push(`ceiling penetration y=${b.pos.y}`);
reset();const base=G.makeBody({name:'base',w:1.5,d:1.3,h:.8,mass:35,x:0,y:.4,z:0,material:'wood'}),top=G.makeBody({name:'top',w:.65,d:.6,h:.5,mass:4,x:0,y:1.055,z:0,material:'cardboard'});S.bodies=[base,top];for(let i=0;i<900;i++)G.stepPhysics(1/120);if(!finite(base)||!finite(top)||top.pos.y<.76)failures.push(`vertical stacking collapsed y=${top.pos.y}`);
reset();const mug=G.makeBody({name:'mug',w:.16,d:.16,h:.18,mass:.34,x:0,y:.09,z:0,material:'ceramic'});mug.fragile=true;mug.breakImpulse=5;S.bodies=[mug];G.impactEventV2(mug,null,4,{...mug.pos},{x:1,y:0,z:0});if(mug.broken)failures.push('fragile item broke below threshold');G.impactEventV2(mug,null,8,{...mug.pos},{x:1,y:0,z:0});if(!mug.broken||S.bodies.filter(x=>x.fragment).length<3||S.bodies.filter(x=>x.fragment).length>6)failures.push('bounded destruction threshold/fragments failed');
let seed=0xC0FFEE;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);for(let caseNo=0;caseNo<1000;caseNo++){reset();S.statics=[G.makeStatic(0,1.3,0,.28,2.6,8,{material:'stone',yaw:(rnd()-.5)*.7}),G.makeStatic(4,1.3,2,5,2.6,.32,{material:'stone',yaw:(rnd()-.5)*.5})];const count=1+(rnd()*4|0);for(let i=0;i<count;i++){const q=G.makeBody({name:'fuzz',w:.25+rnd()*3.2,d:.25+rnd()*2.5,h:.18+rnd()*1.8,mass:.2+rnd()*145,x:-5+rnd()*8,y:.2+rnd()*2.4,z:-3+rnd()*6,yaw:(rnd()-.5)*Math.PI*2,material:['wood','metal','fabric','rubber','stone','cardboard','ceramic','glass'][rnd()*8|0],profile:{linearDamping:.15+rnd()*1.4,angularDamping:.25+rnd()*2.2}});q.vel.x=(rnd()-.5)*100;q.vel.z=(rnd()-.5)*100;q.vel.y=(rnd()-.5)*12;q.ang=(rnd()-.5)*34;S.bodies.push(q)}for(let i=0;i<240;i++)G.stepPhysics(i%19===0?1/24:1/120);for(const q of S.bodies){if(!finite(q)){failures.push(`NaN case ${caseNo}`);break}if(Math.hypot(q.vel.x,q.vel.z)>180||Math.abs(q.ang)>140){failures.push(`explosive velocity case ${caseNo}`);break}}}
if(failures.length){console.error(failures.slice(0,30).join('\n'));process.exit(1)}console.log('V2 physics fuzz PASS: sleeping + CCD + ceiling + stacking + bounded destruction + 1000 randomized scenarios x 240 steps.');
